version: "3.1"

services:
  pascal:
    build: 
      context: .
      dockerfile: Dockerfile.pascalfc
    volumes:
      - ./unidad_1:/home
  mpi_openmp:
    build: 
      context: .
      dockerfile: Dockerfile.mpi_openmp
    volumes:
      - ./unidad_3:/home
  haskell_prolog:
    build: 
      context: .
      dockerfile: Dockerfile.haskell_prolog
    volumes: 
      - ./unidad_4:/home
      - /home/javascript/node_modules
    ports: 
      - 3000:3000
  firebase:
    build: 
      context: .
      dockerfile: Dockerfile.firebase
    volumes: 
      - ./unidad_6:/var/www/html
    ports: 
      - 3002:80